### ISSUE TITLE
circushttpd not working

### ISSUE THREAD

**Issue by rongfengliang** [rongfengliang/circus-docker#1]
exception message 

```code
web_1     | SyntaxError: invalid syntax
web_1     | Traceback (most recent call last):
web_1     |   File "<string>", line 1, in <module>
web_1     |   File "/usr/local/lib/python3.7/site-packages/circusweb/circushttpd.py", line 25, in <module>
web_1     |     import tornadio2
web_1     |   File "/usr/local/lib/python3.7/site-packages/tornadio2/__init__.py", line 25, in <module>
web_1     |     from tornadio2.router import TornadioRouter
web_1     |   File "/usr/local/lib/python3.7/site-packages/tornadio2/router.py", line 27, in <module>
web_1     |     from tornadio2 import persistent, polling, sessioncontainer, session, proto, preflight, stats
web_1     |   File "/usr/local/lib/python3.7/site-packages/tornadio2/persistent.py", line 143
web_1     |     except Exception, ex:
web_1     |                     ^
web_1     | SyntaxError: invalid syntax
```

**Comment by rongfengliang** [comment]
the reason  is the version of python change to low version 2.7 works but other verison don't test 

use `dalongrong/circus:2.7-slim-stretch`
