### ISSUE TITLE
web connect zermq error

### ISSUE THREAD

**Issue by rongfengliang** [rongfengliang/circus-docker#2]
error message

```code
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1468, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1681, in future_complete
    f.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/site-packages/circusweb/circushttpd.py", line 164, in post
    endpoints = self.get_arguments('endpoint_list', [])
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 417, in get_arguments
    assert isinstance(strip, bool)
AssertionError
```

**Comment by rongfengliang** [comment]
some links  for this issue 
https://github.com/circus-tent/circus-web/issues/59

**Comment by rongfengliang** [comment]
bug fixed 

```code
 pip uninstall -y tornado 
 pip install tornado==3.2.2
```
